/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Pregunta;
import modelo.Respuesta;
import modelo.Usuario;
import modelo.UsuarioAcademico;
import modelo.Voto;

/**
 *
 * @author kachu
 */
public class ViewRespuesta extends javax.swing.JFrame {

    private final Controlador controlador;
    private JFrame previo;
    private Usuario user;
    private Pregunta pregunta;

    /**
     * Creates new form ViewRespuesta
     */
    public ViewRespuesta(Controlador c, JFrame prev, Usuario u, Pregunta p) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.controlador = c;
        this.previo = prev;
        this.user = u;
        this.pregunta = p;
        this.labelPregunta.setText(p.getTitulo());
        recargarRespuestas();
        if (user.getTipoUsuario().equals(Usuario.ESTUDIANTE) | user.getTipoUsuario().equals(Usuario.PROFESOR)) {
            this.btnEliminar.setVisible(false);
            this.btnEditarRespuesta.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPregunta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRespuestas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        btnPublicarRespuesta = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDetalles = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        btnLike = new javax.swing.JButton();
        btnDislike = new javax.swing.JButton();
        labelVotPos = new javax.swing.JLabel();
        labelVotNeg = new javax.swing.JLabel();
        btnEditarRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelPregunta.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labelPregunta.setText("Pregunta....");

        listaRespuestas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaRespuestasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaRespuestas);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Respuestas");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Nueva respuesta");

        btnPublicarRespuesta.setText("Publicar");
        btnPublicarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarRespuestaActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaDetalles);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Info");

        btnLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/megusta.png"))); // NOI18N
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });

        btnDislike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nomegusta.png"))); // NOI18N
        btnDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDislikeActionPerformed(evt);
            }
        });

        btnEditarRespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPregunta)
                        .addContainerGap(631, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnPublicarRespuesta)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(btnEditarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(labelVotPos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(labelVotNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDislike, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPregunta)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPublicarRespuesta)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVotNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDislike, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVotPos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarRespuestaActionPerformed
        if (!txtRespuesta.getText().isEmpty()) {
            String respuesta = this.txtRespuesta.getText();
            this.controlador.publicarRespuesta(respuesta, (UsuarioAcademico) user, pregunta);
            this.controlador.sumarReputacion((UsuarioAcademico) user);
            this.txtRespuesta.setText("");
            recargarRespuestas();
        }else{
            JOptionPane.showMessageDialog(null, "Cargue el campo");
        }


    }//GEN-LAST:event_btnPublicarRespuestaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();

        this.controlador.eliminarRespuesta(r);
        this.listaRespuestas.clearSelection();
        recargarRespuestas();
//        DefaultListModel modelo = new DefaultListModel();
//        modelo.add(0, "nada");
//        this.listaDetalles.setModel(modelo);


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void listaRespuestasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaRespuestasValueChanged
        if (!listaRespuestas.isSelectionEmpty()) {
            cargarDetalles();
        }


    }//GEN-LAST:event_listaRespuestasValueChanged

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        if (!listaRespuestas.isSelectionEmpty()) {
            Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();
            System.out.println("ver " + user);
            this.controlador.votarRespuesta(r, true, (UsuarioAcademico) user);
            cargarVotos();
        }
    }//GEN-LAST:event_btnLikeActionPerformed

    private void btnDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDislikeActionPerformed
        if (!listaRespuestas.isSelectionEmpty()) {
            Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();
            this.controlador.votarRespuesta(r, false, (UsuarioAcademico) user);
            cargarVotos();
        }


    }//GEN-LAST:event_btnDislikeActionPerformed

    private void btnEditarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRespuestaActionPerformed
        if (!listaRespuestas.isSelectionEmpty()) {
            Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();
            ViewEditResp ver = new ViewEditResp(controlador, this, r);
            this.setEnabled(false);
            ver.setVisible(true);
            ver.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnEditarRespuestaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!listaRespuestas.isSelectionEmpty()) {
            recargarRespuestas();
        }
    }//GEN-LAST:event_formWindowActivated

    public void recargarRespuestas() {

        List<Respuesta> respuestas = this.controlador.verRespuestas(pregunta);
        this.listaRespuestas.setListData(respuestas.toArray());
    }

    private void cargarDetalles() {
        DefaultListModel modelo = new DefaultListModel();
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yy HH:mm");

        Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();
        List<Object> detalles = this.controlador.verDetalleRespuesta(r);
        modelo.add(0, "Usuario: " + detalles.get(0));
        modelo.add(1, "Fecha: " + detalles.get(1));
        modelo.add(2, "Cantidad de votos positivos: " + detalles.get(2));
        modelo.add(3, "Cantidad de votos negativos: " + detalles.get(3));

        this.listaDetalles.setModel(modelo);
        cargarVotos();

    }

    private void cargarVotos() {
        if (!listaRespuestas.isSelectionEmpty()) {
            Respuesta r = (Respuesta) this.listaRespuestas.getSelectedValue();
            this.labelVotPos.setText(Integer.toString(this.controlador.obtenerCantVotosPositivos(r)));
            this.labelVotNeg.setText(Integer.toString(this.controlador.obtenerCantVotosNegativos(r)));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDislike;
    private javax.swing.JButton btnEditarRespuesta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnPublicarRespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JLabel labelVotNeg;
    private javax.swing.JLabel labelVotPos;
    private javax.swing.JList listaDetalles;
    private javax.swing.JList listaRespuestas;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
