/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Foro;
import modelo.Materia;
import modelo.Pregunta;
import modelo.Usuario;
import modelo.UsuarioAcademico;

/**
 *
 * @author kachu
 */
public class ViewMenu extends javax.swing.JFrame {

    private final Controlador controlador;
    private Usuario user;
    private JFrame previo;

    /**
     * Creates new form viewMenu
     */
    public ViewMenu(Controlador c, Usuario u, JFrame p) {
        initComponents();
        this.controlador = c;
        this.user = u;
        this.previo = p;

        recargarForos();
        cargarComboTipoUser();
        recargarMaterias();
        setToolTip();
        cargarPermisos();
        recargarUsuarios();

        this.labelSaludo.setText("Hola " + user.getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        panelUsers = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaForos = new javax.swing.JList();
        btnNuevoForo = new javax.swing.JButton();
        btnEliminarForo = new javax.swing.JButton();
        btnEntrarForo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMaterias = new javax.swing.JList();
        txtMateria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGuardarMateria = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditarMate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        txtApellidoUser = new javax.swing.JTextField();
        txtDniUser = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        txtPassUser = new javax.swing.JPasswordField();
        comboTipoUser = new javax.swing.JComboBox();
        btnCrearUser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList();
        btnEditarPerfil = new javax.swing.JButton();
        btnEliminarPerfil = new javax.swing.JButton();
        btnVerPerfil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        comboFiltro = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaBusqueda = new javax.swing.JList();
        btnVerMas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnPerfilUser = new javax.swing.JButton();
        labelSaludo = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listaForos.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        listaForos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaForosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaForos);

        btnNuevoForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
        btnNuevoForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoForoActionPerformed(evt);
            }
        });

        btnEliminarForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarForoActionPerformed(evt);
            }
        });

        btnEntrarForo.setText("Entrar");
        btnEntrarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarForoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("Listado de Foros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(btnEliminarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevoForo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(btnEntrarForo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnEntrarForo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoForo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        panelUsers.addTab("Foros", jPanel1);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Listado de Materias");

        listaMaterias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMateriasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaMaterias);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Materia");

        btnGuardarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
        btnGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateriaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setText("Link");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditarMate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarMate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(txtLink)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarMate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelUsers.addTab("Materias", jPanel4);

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI");

        jLabel5.setText("Tipo de Usuario");

        jLabel6.setText("Email");

        jLabel7.setText("Password");

        btnCrearUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnCrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(txtApellidoUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDniUser)
                        .addComponent(txtEmailUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPassUser))
                    .addComponent(btnCrearUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(comboTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelUsers.addTab("Crear Usuarios", jPanel2);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("Listado de Usuarios");

        jScrollPane4.setViewportView(listUsuarios);

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editarPerfil.png"))); // NOI18N
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        btnEliminarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarPerfil.png"))); // NOI18N
        btnEliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPerfilActionPerformed(evt);
            }
        });

        btnVerPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verPerfil.png"))); // NOI18N
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVerPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel20))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        panelUsers.addTab("Ver Usuarios", jPanel5);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PREGUNTA", "FORO", "USUARIO" }));

        jScrollPane3.setViewportView(listaBusqueda);

        btnVerMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vermas.png"))); // NOI18N
        btnVerMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerMas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerMas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );

        panelUsers.addTab("Buscar Preguntas", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("Menu Principal");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPerfilUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verPerfil.png"))); // NOI18N
        btnPerfilUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilUserActionPerformed(evt);
            }
        });

        labelSaludo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        labelSaludo.setText("Nombre..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSaludo)
                .addGap(18, 18, 18)
                .addComponent(btnPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelUsers)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelSaludo))
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsers))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (listaForos.isSelectionEmpty()) {
            recargarForos();
        }

    }//GEN-LAST:event_formWindowActivated

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        previo.setVisible(true);
        previo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed

        if (!listUsuarios.isSelectionEmpty()) {
            Usuario u = (Usuario) this.listUsuarios.getSelectedValue();
            if (u.getTipoUsuario().equals(Usuario.REGISTRADOR)) {
                JOptionPane.showMessageDialog(null, "Los registradores no tiene perfil");
            } else {
                ViewPerfilUser vpu = new ViewPerfilUser(controlador, this, u);
                vpu.setVisible(true);
                vpu.setLocationRelativeTo(null);
                this.dispose();
            }
        }


    }//GEN-LAST:event_btnVerPerfilActionPerformed

    private void btnEliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPerfilActionPerformed
        if (!listUsuarios.isSelectionEmpty()) {
            Usuario u = (Usuario) this.listUsuarios.getSelectedValue();
            this.controlador.eliminarUsuario(u);
            recargarUsuarios();
        }

    }//GEN-LAST:event_btnEliminarPerfilActionPerformed

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        if (!this.listUsuarios.isSelectionEmpty()) {
            Usuario u = (Usuario) this.listUsuarios.getSelectedValue();
            this.dispose();
            ViewEditPerfil vp = new ViewEditPerfil(controlador, this, u);
            vp.setVisible(true);
            vp.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnCrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUserActionPerformed
        if (txtApellidoUser.getText().isEmpty() | txtNombreUser.getText().isEmpty() | txtDniUser.getText().isEmpty() | txtEmailUser.getText().isEmpty() | txtPassUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete los campos");
        } else {

            String nombre = this.txtNombreUser.getText();
            String apellido = this.txtApellidoUser.getText();
            String dni = this.txtDniUser.getText();
            String tipoUser = (String) this.comboTipoUser.getSelectedItem();
            String email = this.txtEmailUser.getText();
            String pass = this.txtPassUser.getText();
            this.controlador.registrarUsuario(nombre, apellido, dni, tipoUser, email, pass);
            JOptionPane.showMessageDialog(null, "Se creo el usuario");
            this.txtApellidoUser.setText("");
            this.txtNombreUser.setText("");
            this.txtDniUser.setText("");
            this.txtEmailUser.setText("");
            this.txtPassUser.setText("");
            this.recargarUsuarios();
        }
    }//GEN-LAST:event_btnCrearUserActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Materia m = (Materia) this.listaMaterias.getSelectedValue();
        this.controlador.eliminarMateria(m);
        recargarMaterias();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        if (txtMateria.getText().isEmpty() | txtLink.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete los campos");
        } else {

            String materia = this.txtMateria.getText();
            String link = this.txtLink.getText();
            this.controlador.crearMateria(materia, link);
            recargarMaterias();
            this.txtMateria.setText("");
            this.txtLink.setText("");
        }
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    private void btnEntrarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarForoActionPerformed
        if (!listaForos.isSelectionEmpty()) {
            ViewPregunta vp = new ViewPregunta(controlador, this, (Foro) this.listaForos.getSelectedValue(), user);
            vp.setLocationRelativeTo(null);
            vp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnEntrarForoActionPerformed

    private void btnEliminarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarForoActionPerformed
        if (!listaForos.isSelectionEmpty()) {
            Foro f = (Foro) this.listaForos.getSelectedValue();
            this.controlador.eliminarForo(f);
            recargarForos();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un foro");
        }
    }//GEN-LAST:event_btnEliminarForoActionPerformed

    private void btnNuevoForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoForoActionPerformed
        this.listaForos.clearSelection();
        this.setEnabled(false);
        ViewForo vf = new ViewForo(controlador, this);
        vf.setLocationRelativeTo(null);
        vf.setVisible(true);
    }//GEN-LAST:event_btnNuevoForoActionPerformed

    private void listaForosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaForosValueChanged

    }//GEN-LAST:event_listaForosValueChanged

    private void btnPerfilUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilUserActionPerformed
        ViewPerfilUser vpu = new ViewPerfilUser(controlador, this, user);
        vpu.setVisible(true);
        vpu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPerfilUserActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txtBusqueda.getText().equals("")) {
            String filtro = (String) this.comboFiltro.getSelectedItem();
            String busqueda = this.txtBusqueda.getText();
            List<Pregunta> resul = this.controlador.buscarPregunta(filtro, busqueda);
            this.listaBusqueda.setListData(resul.toArray());

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese algo para buscar");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        if (txtBusqueda.getText().length() >= 2) {
            String filtro = (String) this.comboFiltro.getSelectedItem();
            String busqueda = this.txtBusqueda.getText();
            List<Pregunta> resul = this.controlador.buscarPregunta(filtro, busqueda);
            this.listaBusqueda.setListData(resul.toArray());
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnVerMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMasActionPerformed
        if (!listaBusqueda.isSelectionEmpty()) {
            Pregunta p = (Pregunta) this.listaBusqueda.getSelectedValue();
            ViewRespuesta vp = new ViewRespuesta(controlador, this, user, p);
            vp.setVisible(true);
            vp.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnVerMasActionPerformed

    private void btnEditarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMateActionPerformed
        Materia m = (Materia) this.listaMaterias.getSelectedValue();
        String nombre = this.txtMateria.getText();
        String link = this.txtLink.getText();
        this.controlador.modificarMateria(m, nombre, link);
        recargarMaterias();
    }//GEN-LAST:event_btnEditarMateActionPerformed

    private void listaMateriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMateriasValueChanged
        if (!listaMaterias.isSelectionEmpty()) {
            Materia m = (Materia) this.listaMaterias.getSelectedValue();
            this.txtMateria.setText(m.getNombre());
            this.txtLink.setText(m.getEnlace());
        }

    }//GEN-LAST:event_listaMateriasValueChanged

    private void recargarMaterias() {
        this.listaMaterias.setListData(this.controlador.listarMaterias().toArray());
    }

    private void recargarForos() {
        this.listaForos.setListData(this.controlador.verForos().toArray());
    }

    private void cargarComboTipoUser() {
        List<String> elementos = new ArrayList<>();
        if (user.getTipoUsuario().equals("REGISTRADOR")) {
            elementos.add(Usuario.ESTUDIANTE);
            elementos.add(Usuario.PROFESOR);
            //elementos.add(Usuario.REGISTRADOR);
        } else {
            elementos.add(Usuario.ADMINISTRADOR);
            elementos.add(Usuario.ESTUDIANTE);
            elementos.add(Usuario.PROFESOR);
            elementos.add(Usuario.REGISTRADOR);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(elementos.toArray());
        this.comboTipoUser.setModel(modelo);
    }

    public void setToolTip() {
        this.btnSalir.setToolTipText("Cerrar Sesion");
        this.btnEntrarForo.setToolTipText("Entrar al curso seleccionado");
        this.btnPerfilUser.setToolTipText("Mi perfil");
    }

    public void cargarPermisos() {

        if (Usuario.ESTUDIANTE.equals(user.getTipoUsuario()) | Usuario.PROFESOR.equals(user.getTipoUsuario())) {
            this.btnEliminarForo.setVisible(false);
            this.btnNuevoForo.setVisible(false);
            this.panelUsers.setEnabledAt(1, false);
            this.panelUsers.setEnabledAt(2, false);
            this.btnEditarPerfil.setVisible(false);
            this.btnEliminarPerfil.setVisible(false);
        } else if (Usuario.REGISTRADOR.equals(user.getTipoUsuario())) {
            this.panelUsers.setEnabledAt(0, false);
            this.panelUsers.setEnabledAt(1, false);
            this.panelUsers.setEnabledAt(4, false);
            this.panelUsers.setSelectedIndex(2);
            this.btnEditarPerfil.setVisible(false);
            this.btnEliminarPerfil.setVisible(false);
            this.btnPerfilUser.setEnabled(false);
        }
    }

    private void recargarUsuarios() {
        this.listUsuarios.setListData(this.controlador.listarUsuarios().toArray());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearUser;
    private javax.swing.JButton btnEditarMate;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarForo;
    private javax.swing.JButton btnEliminarPerfil;
    private javax.swing.JButton btnEntrarForo;
    private javax.swing.JButton btnGuardarMateria;
    private javax.swing.JButton btnNuevoForo;
    private javax.swing.JButton btnPerfilUser;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerMas;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JComboBox comboTipoUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelSaludo;
    private javax.swing.JList listUsuarios;
    private javax.swing.JList listaBusqueda;
    private javax.swing.JList listaForos;
    private javax.swing.JList listaMaterias;
    private javax.swing.JTabbedPane panelUsers;
    private javax.swing.JTextField txtApellidoUser;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDniUser;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNombreUser;
    private javax.swing.JPasswordField txtPassUser;
    // End of variables declaration//GEN-END:variables
}
